import type { ThemeName } from './themes';

export interface BackgroundDef {
  id: string;
  label: string;
  file: string;
}

const BASE = '/DevDesh/backgrounds/';

export const BACKGROUNDS: BackgroundDef[] = [
  { id: 'redgate-dark-geo', label: 'Dark Geometric', file: `${BASE}redgate-dark-geo.jpg` },
  { id: 'redgate-dark-gradient', label: 'Dark Gradient', file: `${BASE}redgate-dark-gradient.jpg` },
  { id: 'glass-colorful', label: 'Colorful Gradient', file: `${BASE}glass-colorful-gradient.jpg` },
  { id: 'glass-aurora', label: 'Aurora', file: `${BASE}glass-aurora.jpg` },
  { id: 'metro-geometric', label: 'Bold Geometric', file: `${BASE}metro-bold-geometric.jpg` },
  { id: 'metro-vibrant', label: 'Vibrant Abstract', file: `${BASE}metro-vibrant-abstract.jpg` },
  { id: 'fluent-bloom', label: 'Blue Bloom', file: `${BASE}fluent-blue-bloom.jpg` },
  { id: 'fluent-flow', label: 'Light Flow', file: `${BASE}fluent-light-flow.jpg` },
  { id: 'win95-clouds', label: 'Clouds', file: `${BASE}win95-clouds.jpg` },
  { id: 'win95-teal', label: 'Teal Retro', file: `${BASE}win95-teal-retro.jpg` },
  { id: 'win95-vaporwave', label: 'Retro Vaporwave', file: `${BASE}win95-vaporwave.jpg` },
  { id: 'winxp-bliss', label: 'Bliss', file: `${BASE}winxp-bliss.jpg` },
  { id: 'general-mountain', label: 'Mountain Landscape', file: `${BASE}general-mountain-landscape.jpg` },
  { id: 'macos9-classic', label: 'Retro Blue', file: `${BASE}macos9-classic.jpg` },
  { id: 'aqua-blue', label: 'Aqua Blue', file: `${BASE}aqua-blue.jpg` },
  { id: 'vista-aurora', label: 'Vista Aurora', file: `${BASE}vista-aurora.jpg` },
  { id: 'cyberpunk-neon', label: 'Neon City', file: `${BASE}cyberpunk-neon.jpg` },
  { id: 'nord-arctic', label: 'Arctic', file: `${BASE}nord-arctic.jpg` },
  { id: 'dracula-purple', label: 'Purple Night', file: `${BASE}dracula-purple.jpg` },
  { id: 'solarized-warm', label: 'Warm Sunset', file: `${BASE}solarized-warm.jpg` },
  { id: 'catppuccin-pastel', label: 'Pastel Gradient', file: `${BASE}catppuccin-pastel.jpg` },
  { id: 'synthwave-sunset', label: 'Synthwave Sunset', file: `${BASE}synthwave-sunset.jpg` },
  { id: 'terminal-matrix', label: 'Matrix', file: `${BASE}terminal-matrix.jpg` },
  { id: 'amiga-workbench', label: 'Amiga', file: `${BASE}amiga-workbench.jpg` },
  { id: 'beos-desktop', label: 'BeOS', file: `${BASE}beos-desktop.jpg` },
  { id: 'ubuntu-warty', label: 'Ubuntu Warty', file: `${BASE}ubuntu-warty.png` },
  { id: 'ios-gradient', label: 'iOS Gradient', file: `${BASE}ios-gradient.jpg` },
  { id: 'android-material', label: 'Material', file: `${BASE}android-material.jpg` },
  { id: 'chromeos-blue', label: 'Chrome Blue', file: `${BASE}chromeos-blue.jpg` },
  { id: 'irix-indigo', label: 'IRIX Indigo', file: `${BASE}irix-indigo.jpg` },
  { id: 'palmos-warm', label: 'Palm OS', file: `${BASE}palmos-warm.jpg` },
  { id: 'c64-blue', label: 'C64 Blue', file: `${BASE}c64-blue.jpg` },
  { id: 'carbon-dark', label: 'Carbon Dark', file: `${BASE}carbon-dark.jpg` },
  { id: 'hig-light', label: 'Apple HIG', file: `${BASE}hig-light.jpg` },
  { id: 'gruvbox-warm', label: 'Gruvbox Warm', file: `${BASE}gruvbox-warm.jpg` },
  { id: 'monokai-dark', label: 'Monokai', file: `${BASE}monokai-dark.jpg` },
  { id: 'onedark-space', label: 'One Dark', file: `${BASE}onedark-space.jpg` },
  { id: 'win31-pattern', label: 'Win 3.1', file: `${BASE}win31-pattern.jpg` },
  { id: 'gnome-abstract', label: 'GNOME', file: `${BASE}gnome-abstract.jpg` },
  { id: 'sonoma-landscape', label: 'Sonoma', file: `${BASE}sonoma-landscape.jpg` },
  { id: 'highcontrast-dark', label: 'High Contrast', file: `${BASE}highcontrast-dark.jpg` },
  { id: 'paper-minimal', label: 'Paper', file: `${BASE}paper-minimal.jpg` },
  { id: 'vaporwave-aesthetic', label: 'Vaporwave', file: `${BASE}vaporwave-aesthetic.jpg` },
  { id: 'general-space', label: 'Space Galaxy', file: `${BASE}general-space-galaxy.jpg` },
  { id: 'general-minimalist', label: 'Minimalist Gradient', file: `${BASE}general-minimalist-gradient.jpg` },
  { id: 'tos-lcars', label: 'LCARS', file: `${BASE}tos-lcars.svg` },
  { id: 'templeos-blue', label: 'TempleOS Blue', file: `${BASE}templeos-blue.svg` },
  { id: 'haiku-desktop', label: 'Haiku', file: `${BASE}haiku-desktop.svg` },
  { id: 'plan9-rio', label: 'Plan 9 Rio', file: `${BASE}plan9-rio.svg` },
  { id: 'solaris-cde', label: 'Solaris CDE', file: `${BASE}solaris-cde.svg` },
  { id: 'win10-hero', label: 'Win 10 Hero', file: `${BASE}win10-hero.svg` },
  { id: 'kde-breeze', label: 'KDE Breeze', file: `${BASE}kde-breeze.svg` },
  { id: 'mint-cinnamon', label: 'Mint Cinnamon', file: `${BASE}mint-cinnamon.svg` },
  { id: 'redhat-desktop', label: 'Red Hat', file: `${BASE}redhat-desktop.svg` },
  { id: 'zxspectrum-rainbow', label: 'ZX Rainbow', file: `${BASE}zxspectrum-rainbow.svg` },
  { id: 'atari-gem', label: 'Atari GEM', file: `${BASE}atari-gem.svg` },
  { id: 'symbian-blue', label: 'Symbian', file: `${BASE}symbian-blue.svg` },
  { id: 'riscos-cream', label: 'RISC OS', file: `${BASE}riscos-cream.svg` },
  { id: 'webos-cards', label: 'webOS', file: `${BASE}webos-cards.svg` },
  { id: 'windowsphone-tiles', label: 'Windows Phone', file: `${BASE}windowsphone-tiles.svg` },
  { id: 'blackberry-dark', label: 'BlackBerry', file: `${BASE}blackberry-dark.svg` },
  { id: 'tizen-blue', label: 'Tizen', file: `${BASE}tizen-blue.svg` },
  { id: 'sailfish-amber', label: 'Sailfish', file: `${BASE}sailfish-amber.svg` },
  { id: 'openstep-grey', label: 'OpenStep', file: `${BASE}openstep-grey.svg` },
  { id: 'morphos-blue', label: 'MorphOS', file: `${BASE}morphos-blue.svg` },
  { id: 'reactos-silver', label: 'ReactOS', file: `${BASE}reactos-silver.svg` },
  { id: 'hpux-tan', label: 'HP-UX CDE', file: `${BASE}hpux-tan.svg` },
  { id: 'spongebob-ocean', label: 'Bikini Bottom', file: `${BASE}spongebob-ocean.jpg` },
  { id: 'ateam-military', label: 'A-Team', file: `${BASE}ateam-military.jpg` },
  { id: 'starwars-space', label: 'Galaxy', file: `${BASE}starwars-space.jpg` },
  { id: 'matrix-code', label: 'Digital Rain', file: `${BASE}matrix-code.jpg` },
  { id: 'barbie-pink', label: 'Pink Dream', file: `${BASE}barbie-pink.jpg` },
  { id: 'batman-gotham', label: 'Gotham', file: `${BASE}batman-gotham.jpg` },
  { id: 'jurassicpark-jungle', label: 'Jungle', file: `${BASE}jurassicpark-jungle.jpg` },
  { id: 'simpsons-suburb', label: 'Springfield', file: `${BASE}simpsons-suburb.jpg` },
  { id: 'ghostbusters-fog', label: 'Foggy Night', file: `${BASE}ghostbusters-fog.jpg` },
  { id: 'tron-neon', label: 'Neon Grid', file: `${BASE}tron-neon.jpg` },
];

/** Default background for each theme (applied when switching themes) */
export const THEME_DEFAULT_BACKGROUND: Record<ThemeName, string> = {
  redgate: '',
  glass: 'glass-colorful',
  metro: '',
  fluent: 'fluent-bloom',
  win95: 'win95-clouds',
  winxp: 'winxp-bliss',
  macos9: 'macos9-classic',
  aqua: 'aqua-blue',
  vista: 'vista-aurora',
  cyberpunk: 'cyberpunk-neon',
  nord: 'nord-arctic',
  dracula: 'dracula-purple',
  solarized: '',
  catppuccin: '',
  synthwave: 'synthwave-sunset',
  terminal: 'terminal-matrix',
  amiga: 'amiga-workbench',
  beos: 'beos-desktop',
  ubuntu: 'ubuntu-warty',
  ios: 'ios-gradient',
  android: 'android-material',
  chromeos: 'chromeos-blue',
  nextstep: 'macos9-classic',
  os2: 'beos-desktop',
  irix: 'irix-indigo',
  palmos: '',
  c64: '',
  msdos: 'highcontrast-dark',
  carbon: 'carbon-dark',
  hig: '',
  ant: 'macos9-classic',
  gruvbox: '',
  monokai: '',
  onedark: 'onedark-space',
  win31: '',
  gnome: 'gnome-abstract',
  sonoma: 'sonoma-landscape',
  highcontrast: '',
  paper: '',
  vaporwave: 'vaporwave-aesthetic',
  tos: 'tos-lcars',
  templeos: 'templeos-blue',
  haiku: 'haiku-desktop',
  plan9: 'plan9-rio',
  solaris: 'solaris-cde',
  win10: 'win10-hero',
  kde: 'kde-breeze',
  mint: 'mint-cinnamon',
  redhat: 'redhat-desktop',
  zxspectrum: 'zxspectrum-rainbow',
  atari: 'atari-gem',
  symbian: 'symbian-blue',
  tokyonight: '',
  everforest: '',
  rosepine: '',
  kanagawa: '',
  ayu: '',
  retrowave: '',
  cottagecore: '',
  brutalist: '',
  riscos: 'riscos-cream',
  webos: 'webos-cards',
  windowsphone: 'windowsphone-tiles',
  blackberry: 'blackberry-dark',
  tizen: 'tizen-blue',
  sailfish: 'sailfish-amber',
  openstep: 'openstep-grey',
  morphos: 'morphos-blue',
  reactos: 'reactos-silver',
  hpux: 'hpux-tan',
  material: '',
  nightowl: '',
  vitesse: '',
  palenight: '',
  cobalt: '',
  solarpunk: '',
  y2k: '',
  noir: '',
  pastel: '',
  steampunk: '',
  facebook: '',
  youtube: '',
  netflix: '',
  ebay: '',
  amazon: '',
  spotify: '',
  twitter: '',
  reddit: '',
  github_theme: '',
  stackoverflow: '',
  twitch: '',
  discord: '',
  slack: '',
  linkedin: '',
  wikipedia: '',
  spongebob: 'spongebob-ocean',
  ateam: 'ateam-military',
  starwars: 'starwars-space',
  matrix: 'matrix-code',
  barbie: 'barbie-pink',
  batman: 'batman-gotham',
  jurassicpark: 'jurassicpark-jungle',
  simpsons: 'simpsons-suburb',
  ghostbusters: 'ghostbusters-fog',
  tron: 'tron-neon',
};

export function getBackgroundById(id: string): BackgroundDef | undefined {
  return BACKGROUNDS.find((b) => b.id === id);
}
