import type { ThemeName } from './themes';

export interface BackgroundDef {
  id: string;
  label: string;
  file: string;
}

const BASE = '/DevDesh/backgrounds/';

export const BACKGROUNDS: BackgroundDef[] = [
  { id: 'redgate-dark-geo', label: 'Dark Geometric', file: `${BASE}redgate-dark-geo.jpg` },
  { id: 'redgate-dark-gradient', label: 'Dark Gradient', file: `${BASE}redgate-dark-gradient.jpg` },
  { id: 'glass-colorful', label: 'Colorful Gradient', file: `${BASE}glass-colorful-gradient.jpg` },
  { id: 'glass-aurora', label: 'Aurora', file: `${BASE}glass-aurora.jpg` },
  { id: 'metro-geometric', label: 'Bold Geometric', file: `${BASE}metro-bold-geometric.jpg` },
  { id: 'metro-vibrant', label: 'Vibrant Abstract', file: `${BASE}metro-vibrant-abstract.jpg` },
  { id: 'fluent-bloom', label: 'Blue Bloom', file: `${BASE}fluent-blue-bloom.jpg` },
  { id: 'fluent-flow', label: 'Light Flow', file: `${BASE}fluent-light-flow.jpg` },
  { id: 'win95-clouds', label: 'Clouds', file: `${BASE}win95-clouds.jpg` },
  { id: 'win95-teal', label: 'Teal Retro', file: `${BASE}win95-teal-retro.jpg` },
  { id: 'win95-vaporwave', label: 'Vaporwave', file: `${BASE}win95-vaporwave.jpg` },
  { id: 'winxp-bliss', label: 'Bliss', file: `${BASE}winxp-bliss.jpg` },
  { id: 'general-mountain', label: 'Mountain Landscape', file: `${BASE}general-mountain-landscape.jpg` },
  { id: 'macos9-classic', label: 'Mac OS 9', file: `${BASE}macos9-classic.jpg` },
  { id: 'aqua-blue', label: 'Aqua Blue', file: `${BASE}aqua-blue.jpg` },
  { id: 'vista-aurora', label: 'Vista Aurora', file: `${BASE}vista-aurora.jpg` },
  { id: 'cyberpunk-neon', label: 'Neon City', file: `${BASE}cyberpunk-neon.jpg` },
  { id: 'nord-arctic', label: 'Arctic', file: `${BASE}nord-arctic.jpg` },
  { id: 'dracula-purple', label: 'Purple Night', file: `${BASE}dracula-purple.jpg` },
  { id: 'solarized-warm', label: 'Warm Sunset', file: `${BASE}solarized-warm.jpg` },
  { id: 'catppuccin-pastel', label: 'Pastel Gradient', file: `${BASE}catppuccin-pastel.jpg` },
  { id: 'synthwave-sunset', label: 'Synthwave Sunset', file: `${BASE}synthwave-sunset.jpg` },
  { id: 'terminal-matrix', label: 'Matrix', file: `${BASE}terminal-matrix.jpg` },
  { id: 'amiga-workbench', label: 'Amiga', file: `${BASE}amiga-workbench.jpg` },
  { id: 'beos-desktop', label: 'BeOS', file: `${BASE}beos-desktop.jpg` },
  { id: 'ubuntu-warty', label: 'Ubuntu Warty', file: `${BASE}ubuntu-warty.png` },
  { id: 'ios-gradient', label: 'iOS Gradient', file: `${BASE}ios-gradient.jpg` },
  { id: 'android-material', label: 'Material', file: `${BASE}android-material.jpg` },
  { id: 'chromeos-blue', label: 'Chrome Blue', file: `${BASE}chromeos-blue.jpg` },
  { id: 'nextstep-dark', label: 'NeXTSTEP', file: `${BASE}nextstep-dark.jpg` },
  { id: 'os2-warp', label: 'OS/2 Warp', file: `${BASE}os2-warp.jpg` },
  { id: 'irix-indigo', label: 'IRIX Indigo', file: `${BASE}irix-indigo.jpg` },
  { id: 'palmos-warm', label: 'Palm OS', file: `${BASE}palmos-warm.jpg` },
  { id: 'c64-blue', label: 'C64 Blue', file: `${BASE}c64-blue.jpg` },
  { id: 'msdos-dark', label: 'DOS', file: `${BASE}msdos-dark.jpg` },
  { id: 'carbon-dark', label: 'Carbon Dark', file: `${BASE}carbon-dark.jpg` },
  { id: 'hig-light', label: 'Apple HIG', file: `${BASE}hig-light.jpg` },
  { id: 'ant-blue', label: 'Ant Blue', file: `${BASE}ant-blue.jpg` },
  { id: 'gruvbox-warm', label: 'Gruvbox Warm', file: `${BASE}gruvbox-warm.jpg` },
  { id: 'monokai-dark', label: 'Monokai', file: `${BASE}monokai-dark.jpg` },
  { id: 'onedark-space', label: 'One Dark', file: `${BASE}onedark-space.jpg` },
  { id: 'win31-pattern', label: 'Win 3.1', file: `${BASE}win31-pattern.jpg` },
  { id: 'gnome-abstract', label: 'GNOME', file: `${BASE}gnome-abstract.jpg` },
  { id: 'sonoma-landscape', label: 'Sonoma', file: `${BASE}sonoma-landscape.jpg` },
  { id: 'highcontrast-dark', label: 'High Contrast', file: `${BASE}highcontrast-dark.jpg` },
  { id: 'paper-minimal', label: 'Paper', file: `${BASE}paper-minimal.jpg` },
  { id: 'vaporwave-aesthetic', label: 'Vaporwave', file: `${BASE}vaporwave-aesthetic.jpg` },
  { id: 'general-space', label: 'Space Galaxy', file: `${BASE}general-space-galaxy.jpg` },
  { id: 'general-minimalist', label: 'Minimalist Gradient', file: `${BASE}general-minimalist-gradient.jpg` },
];

/** Default background for each theme (applied when switching themes) */
export const THEME_DEFAULT_BACKGROUND: Record<ThemeName, string> = {
  redgate: '',
  glass: 'glass-colorful',
  metro: '',
  fluent: 'fluent-bloom',
  win95: 'win95-clouds',
  winxp: 'winxp-bliss',
  macos9: 'macos9-classic',
  aqua: 'aqua-blue',
  vista: 'vista-aurora',
  cyberpunk: 'cyberpunk-neon',
  nord: 'nord-arctic',
  dracula: 'dracula-purple',
  solarized: '',
  catppuccin: '',
  synthwave: 'synthwave-sunset',
  terminal: 'terminal-matrix',
  amiga: 'amiga-workbench',
  beos: 'beos-desktop',
  ubuntu: 'ubuntu-warty',
  ios: 'ios-gradient',
  android: 'android-material',
  chromeos: 'chromeos-blue',
  nextstep: 'nextstep-dark',
  os2: 'os2-warp',
  irix: 'irix-indigo',
  palmos: '',
  c64: '',
  msdos: '',
  carbon: 'carbon-dark',
  hig: '',
  ant: '',
  gruvbox: '',
  monokai: '',
  onedark: 'onedark-space',
  win31: '',
  gnome: 'gnome-abstract',
  sonoma: 'sonoma-landscape',
  highcontrast: '',
  paper: '',
  vaporwave: 'vaporwave-aesthetic',
};

export function getBackgroundById(id: string): BackgroundDef | undefined {
  return BACKGROUNDS.find((b) => b.id === id);
}
